/**
    A simple synth using sine oscillators, showing use of the voice allocator,
    message converter and envelopes
*/

// Determine the note frequency from the pitch (midi note)
processor Rate [[ main, icon: "icons/clock.svg", iconSize: 24, iconColor: "purple" ]]
{
    input value std::time::Time a [[ pinTop: 5 ]];
    input value float32 b [[ pinTop: 45 ]];
    output value std::time::Time c [[ pinTop: 5 ]];

    void main()
    {
        loop {
            // c <- a * b;
            advance();
        }
    }
}
