processor Gain [[ main, width: 1, height: 1 ]]
{
    input stream float32<2> in [[ pinTop: 5 ]];
    input value float32 on [[ pinTop: 45 ]];

    output stream float32<2> out [[ pinTop: 5 ]];

    /*input value float32 knobValue [[
        widget: "iconButton",
        left: 20,
        top: 35,
        default: 0.5,
        color: "red"
    ]];*/

    const float32 dbMin = -60.0f;
    const float32 dbMax = 12.0f;

    void main()
    {
        loop {
            if (on > 0.5f) {
                out <- in;
            }

            advance();
        }
    }
}
