processor Pan [[ main, width: 1, height: 1 ]]
{
    input stream float32<2> in [[ pinTop: 5 ]];
    output stream float32<2> out [[ pinTop: 5 ]];

    input event float32 knobChange [[
        widget: "knob",
        left: 10,
        top: 20,
        width: 40,
        height: 40,
        default: 0.5,
        color: "blue"
    ]];

    event knobChange(float32 v)
    {
        pan = v;
    }

    float32 pan = 0.0f;
    const float32 PI = 3.14159265358979323846f;

    void main()
    {
        loop {
            float32 angle = 0.5f * PI * pan;

            float32 leftGain = cos(angle);
            float32 rightGain = sin(angle);

            out <- (in[0] * leftGain, in[1] * rightGain);

            advance();
        }
    }
}
